export const SENDER_NAME = process.env.SENDER_NAME || "support";
export const SENDER_EMAIL = process.env.SENDER_EMAIL || "onboarding@resend.dev";

export const USER_ROLES = ["ADMIN", "USER"];
export const COLORS = ["Gold", "Green", "Red"];
export const THEMES = ["Light", "Dark", "System"];

export const REACT_NATIVE_COLORS = [
  // Whites & Off-whites
  "white",
  "snow",
  "whitesmoke",
  "ivory",
  "linen",
  "oldlace",
  "floralwhite",
  "ghostwhite",
  "seashell",
  "cornsilk",
  "beige",
  "antiquewhite",
  "papayawhip",
  "blanchedalmond",
  "bisque",
  "peachpuff",
  "lemonchiffon",
  "lightyellow",
  "honeydew",
  "mintcream",
  "azure",
  "aliceblue",

  // Grays & Blacks
  "black",
  "gray",
  "grey",
  "darkgray",
  "darkgrey",
  "dimgray",
  "dimgrey",
  "lightgray",
  "lightgrey",
  "slategray",
  "lightslategrey",
  "darkslategrey",
  "silver",
  "gainsboro",

  // Blues & Cyans
  "blue",
  "lightblue",
  "dodgerblue",
  "deepskyblue",
  "skyblue",
  "lightskyblue",
  "steelblue",
  "lightsteelblue",
  "cornflowerblue",
  "royalblue",
  "mediumblue",
  "darkblue",
  "navy",
  "midnightblue",
  "aqua",
  "cyan",
  "darkcyan",
  "teal",
  "turquoise",
  "mediumturquoise",
  "paleturquoise",

  // Greens
  "green",
  "darkgreen",
  "forestgreen",
  "seagreen",
  "mediumseagreen",
  "lightgreen",
  "palegreen",
  "springgreen",
  "mediumspringgreen",
  "lime",
  "limegreen",
  "lawngreen",
  "greenyellow",
  "yellowgreen",
  "olive",
  "olivedrab",
  "darkolivegreen",

  // Reds
  "red",
  "darkred",
  "firebrick",
  "crimson",
  "indianred",
  "salmon",
  "darksalmon",
  "lightsalmon",
  "tomato",
  "orangered",

  // Pinks
  "pink",
  "lightpink",
  "hotpink",
  "deeppink",
  "palevioletred",
  "mediumvioletred",
  "mistyrose",

  // Oranges & Yellows
  "orange",
  "darkorange",
  "gold",
  "goldenrod",
  "darkgoldenrod",
  "yellow",
  "khaki",
  "darkkhaki",

  // Purples & Violets
  "purple",
  "indigo",
  "darkmagenta",
  "magenta",
  "fuchsia",
  "orchid",
  "mediumorchid",
  "darkorchid",
  "plum",
  "violet",
  "mediumslateblue",
  "slateblue",
  "rebeccapurple",

  // Browns & Earth tones
  "brown",
  "maroon",
  "saddlebrown",
  "sienna",
  "chocolate",
  "peru",
  "burlywood",
  "tan",
  "rosybrown",
  "navajowhite",
  "wheat",
];
  
