// components/search/FiltersMobileSheet.tsx
"use client";

import React from "react";
import {
  Sheet,
    SheetContent,
      SheetHeader,
        SheetTitle,
          SheetTrigger,
            SheetClose,
            } from "@/components/ui/sheet";
            import { Slider } from "@/components/ui/slider";
            import { Input } from "@/components/ui/input";
            import { Button } from "@/components/ui/button";
            import Rating from "@/components/shared/product/rating";
            import { toSlug } from "@/lib/utils";
            import SelectedFiltersPills from "./selected-filters-pills";

            export default function FiltersMobileSheet({
              open,
                setOpen,
                  totalProducts,
                    selectedFilters,
                      categories,
                        tags,
                          category,
                            tag,
                              rating,
                                minPriceInput,
                                  maxPriceInput,
                                    setMinPriceInput,
                                      setMaxPriceInput,
                                        setPriceRange,
                                          handleFilterChange,
                                            handlePriceApply,
                                              onClearAll,
                                                defaultPriceRange,
                                                }: {
                                                  open: boolean;
                                                    setOpen: (v: boolean) => void;
                                                      totalProducts: number;
                                                        selectedFilters: string[];
                                                          categories: string[];
                                                            tags: string[];
                                                              category: string;
                                                                tag: string;
                                                                  rating: string;
                                                                    minPriceInput: number;
                                                                      maxPriceInput: number;
                                                                        setMinPriceInput: (n: number) => void;
                                                                          setMaxPriceInput: (n: number) => void;
                                                                            setPriceRange: (r: [number, number]) => void;
                                                                              handleFilterChange: (filter: string, value: any) => void;
                                                                                handlePriceApply: () => void;
                                                                                  onClearAll: () => void;
                                                                                    defaultPriceRange: [number, number];
                                                                                    }) {
                                                                                      const handleRemove = (label: string) => {
                                                                                          if (label.includes("Category")) handleFilterChange("category", "all");
                                                                                              else if (label.includes("Tag")) handleFilterChange("tag", "all");
                                                                                                  else if (label.includes("Rating")) handleFilterChange("rating", "all");
                                                                                                      else setPriceRange(defaultPriceRange);
                                                                                                        };

                                                                                                          return (
                                                                                                              <Sheet open={open} onOpenChange={setOpen}>
                                                                                                                    <SheetTrigger asChild>
                                                                                                                            <Button variant="outline">Filters</Button>
                                                                                                                                  </SheetTrigger>

                                                                                                                                        <SheetContent side="left" className="w-[85%] p-0">
                                                                                                                                                {/* FIXED HEADER */}
                                                                                                                                                        <SheetHeader className="bg-card p-4 sticky top-0 border-b z-20">
                                                                                                                                                                  <div className="flex justify-between items-center">
                                                                                                                                                                              <SheetTitle>{totalProducts} results</SheetTitle>
                                                                                                                                                                                          <SheetClose asChild>
                                                                                                                                                                                                        <Button variant="ghost">✕</Button>
                                                                                                                                                                                                                    </SheetClose>
                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                      </SheetHeader>

                                                                                                                                                                                                                                              {/* SCROLL CONTENT */}
                                                                                                                                                                                                                                                      <div className="overflow-y-auto p-4" style={{ maxHeight: "calc(100vh - 70px)" }}>
                                                                                                                                                                                                                                                                {/* SELECTED FILTERS */}
                                                                                                                                                                                                                                                                          {selectedFilters.length > 0 && (
                                                                                                                                                                                                                                                                                      <div className="flex flex-wrap gap-2 mb-4">
                                                                                                                                                                                                                                                                                                    <SelectedFiltersPills selectedFilters={selectedFilters} onRemove={handleRemove} />
                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                          )}

                                                                                                                                                                                                                                                                                                                                    {/* CATEGORY */}
                                                                                                                                                                                                                                                                                                                                              <div className="mb-4">
                                                                                                                                                                                                                                                                                                                                                          <div className="font-bold mb-2">Category</div>
                                                                                                                                                                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                                                                                                                                                                    <button className={`py-1 ${category === "all" ? "text-primary" : ""}`} onClick={() => handleFilterChange("category", "all")}>
                                                                                                                                                                                                                                                                                                                                                                                                    All
                                                                                                                                                                                                                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                          {categories.map((c) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div key={c}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button className={`py-1 ${c === category ? "text-primary" : ""}`} onClick={() => handleFilterChange("category", c)}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {c}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* PRICE */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="mb-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="font-bold mb-2">Price</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Slider
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        value={ [minPriceInput, maxPriceInput] as [number, number] }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      min={0}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    max={10000}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  step={100}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onValueChange={(v) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const arr = v as number[];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                setPriceRange([arr[0], arr[1]]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                setMinPriceInput(arr[0]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                setMaxPriceInput(arr[1]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="flex gap-2 mt-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Input type="number" value={minPriceInput} onChange={(e) => setMinPriceInput(Number(e.target.value))} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Input type="number" value={maxPriceInput} onChange={(e) => setMaxPriceInput(Number(e.target.value))} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Button size="sm" onClick={handlePriceApply}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Apply
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* RATING */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="mb-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="font-bold mb-2">Customer Review</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button onClick={() => handleFilterChange("rating", "all")} className={rating === "all" ? "text-primary" : ""}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              All
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button onClick={() => handleFilterChange("rating", "4")} className={`block mt-2 ${rating === "4" ? "text-primary" : ""}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="flex items-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Rating size={4} rating={4} /> &nbsp; & Up
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* TAG */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="mb-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="font-bold mb-2">Tag</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button className={`py-1 ${tag === "all" ? "text-primary" : ""}`} onClick={() => handleFilterChange("tag", "all")}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  All
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {tags.map((t, i) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div key={i}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button className={`py-1 ${toSlug(t) === tag ? "text-primary" : ""}`} onClick={() => handleFilterChange("tag", toSlug(t))}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {t}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* BOTTOM ACTIONS */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="flex justify-between">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Button variant="outline" onClick={onClearAll}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Clear All
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <SheetClose asChild>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Button>Apply</Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </SheetClose>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </SheetContent>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Sheet>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
